### ISSUE TITLE
Doesn't seem to work if you have 

### ISSUE THREAD

**Issue by kokarl** [bearbyt3z/email-protector.js#23]
Hi,

Nice job, but your script doesn't seem to work if there is a dash in the email address.

Regards,
Karl

**Comment by bearbyt3z** [comment]
Thank you. The issue is resolved by the 6558f2a commit. I've used a more complete regular expression provided by MDN Web Docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#basic_validation
